future: true
permalink: /:title/
url: http://sonhua-deng.github.io
name: Deng Songhua
author: Deng Songhua
qq: 877922601
email: dengsonhua@163.com

duoshuo: 
beian: 
cnzz: 
weibo: 
github:sonhua-deng
about: "这里是 Deng 的个人博客，创建于 2016"

safe: true
paginate: 20
